CREATE TABLE IF NOT EXISTS NOT_HASHED_SGD (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS NOT_HASHED_MULTINOMIALNB (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


##### exotic tables

CREATE TABLE IF NOT EXISTS SGD (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS MULTINOMIALNB (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS BERNOULLINB (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;



CREATE TABLE IF NOT EXISTS RIDGECLASSIFIER (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS PASSIVEAGGRESSIVE (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS KNN (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS LINEARSVCL1 (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS LINEARSVCL2 (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS SGDL1 (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS SGDL2 (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS NEARESTCENTROID (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PERCEPTRON (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS LINEARSVCL1FS (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS LINEARSVCCLASS (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS DECISIONTREE (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS RANDOMFOREST (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS ADABOOSTCLASSIFIER (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

##### production tables

CREATE TABLE IF NOT EXISTS PRODUCTIONPASSIVEAGGRESSIVE (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_LINEARSVCCLASS (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_PASSIVEAGGRESSIVE (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_SGDL1 (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_NEARESTCENTROID (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_MULTINOMIALNB (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_BERNOULLINB (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_KNN (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_SGDL2 (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_ELASTICNET (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_RANDOMFOREST (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_DECISIONTREE (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_ADABOOSTCLASSIFIER (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_SVCRBF (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS PRODUCTION_CLEANED_XGBOOST (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;



 
 

