CREATE TABLE IF NOT EXISTS DL_KNN (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS DL_NB (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS DL_DT (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS DL_AB (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS DL_RF (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS DL_RBF_SVM (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS DL_LDA (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS DL_L_SVM (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS DL_QDA (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS XGBOOST (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;





